# exception_09.py
try:
    x = int(input("Введите число: "))
    print(5/x)
except:
    print("Какая-то ошибка")
